[variables]
NODE_VERSION = "18"

[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = [
  "npm ci --include=dev"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npx serve -s build -l $PORT" 